# -*- coding: utf-8 -*-
"""ANZ_insights.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuuhHPxYLsYzMco-zGxI3JOFwi3ntq3w
"""

import pandas as pd

anz_dataset = pd.read_excel('ANZ synthesised transaction dataset.xlsx')
print(anz_dataset.shape)

#Overall insights about the data
start_date = anz_dataset['date'][0]
end_date = anz_dataset['date'][len(anz_dataset['date'])-1]
print(start_date,end_date)

customer_total = len(set(anz_dataset['customer_id']))
print(customer_total)

trans_amount = sum(anz_dataset['amount'])
print(round(trans_amount,3))

total_debit = sum(anz_dataset[anz_dataset['movement']=='debit']['amount'])
total_credit = sum(anz_dataset[anz_dataset['movement']=='credit']['amount'])
print('Debit: AUD',round(total_debit,3)," and Total credit: AUD", round(total_credit,3))

total_authorized = sum(anz_dataset[anz_dataset['status']=='authorized']['amount'])
total_posted = sum(anz_dataset[anz_dataset['status']=='posted']['amount'])
print('Authorized: AUD',round(total_authorized,3)," and Total Posted: AUD", round(total_posted,3))

#HANDLE BPAY AND MERCHANT CODE COLUMNS
anz_dataset = anz_dataset.drop(['bpay_biller_code','merchant_code','merchant_id'], axis=1)

#FINDING WHICH ROWS HAVE NULL
anz_dataset.isna().any(axis=0)

#Dividing into two datasets (Authorized and Posted)
anz_authorized = anz_dataset[anz_dataset['status']=='authorized']
anz_posted = anz_dataset[anz_dataset['status']=='posted']

anz_posted = anz_posted.dropna(axis = 1, how='any')

#Segment both datasets into date and time

anz_posted['transaction time'] = pd.to_datetime(anz_posted['extraction']).dt.time
anz_authorized['transaction time'] = pd.to_datetime(anz_authorized['extraction']).dt.time

#Drop extraction from both
anz_posted=anz_posted.drop('extraction', axis=1)
anz_authorized=anz_authorized.drop('extraction', axis=1)

#To csv's
anz_authorized.to_csv('ANZ Authorized.csv')
anz_posted.to_csv('ANZ Posted.csv')